
export enum UI_EVENT {
    SWITCH_MOD = "SWITCH_MOD",
    ON_MODSYNC_LISTEN = "ON_MODSYNC_LISTEN",
    OFF_MODSYNC_LISTEN = "OFF_MODSYNC_LISTEN",
    ROOM_LIST = "ROOM_LIST",
    ROOM_INFO = "ROOM_INFO",
    BACK_NORMAL = "BACK_NORMAL",
    MOD_SYNC = "MOD_SYNC",
    PERFORM_MINI_SCENE = "PERFORM_MINI_SCENE",
    CLEAR_MINI_SCENE = "CLEAR_MINI_SCENE",
    GAME_START = "GAME_START",
    IN_ROOM = "IN_ROOM",
}
export enum CONTOLER_ENENT {
    PERSIST_CONTROLER = "PERSIST_CONTROLER",
    SHOW_CONTROLER = "SHOW_CONTROLER"

}
export enum TWEEN_TIME {
    CAROUSEL_TIME = 0.3,
    COLOR_FADE_TIME = 5,
    GLASSBALL_FALL_TIME = 1.5
}
export enum MOD_TYPE {
    MMU = "MMU",
}
export enum GAME_MMU {
    GAME_STATE_MAP = "GAME_STATE_MAP",
    READY_TIME_ON = "READY_TIME_ON",
}
export enum MSG_TYPE {
    ROOM_BROADCAST = "ROOM_BROADCAST",
    JOIN_REQUEST = "JOIN_REQUEST",
    JOIN_ACCEPT = "JOIN_ACCEPT",
    HEART_BEAT = "HEART_BEAT",
    RE_CONECTION = "RE_CONECTION",
    PLAYER_LIST = "PLAYER_LIST",
    SWITCH_NETMOD = "SWITCH_NETMOD",
    OUT_ROOM = "OUT_ROOM",
    GAME_START = "GAME_START",
    GAME_INPUT = "GAME_INPUT",
    GAME_STATE = "GAME_STATE",
    GAME_STATE_MAP = "GAME_STATE_MAP",
    CHARACTER_SYNC = "CHARACTER_SYNC",
    GAME_DEFEAT = "GAME_DEFEAT",//角色死亡
    GAME_END = "GAME_END",//游戏结算
    RE_GAME = "RE_GAME",
    BACK_HALL = "BACK_HALL",

    READY_TIMER = "READY_TIMER"
}